import = [
    "~/.config/alacritty/themes/kanagawa_dragon.toml"
#
# DOWNLOAD FROM:
# https://github.com/alacritty/alacritty-theme
#
# THEMES:
#
# SOFT COLORS:
#
# - autumn
# - citylights
# - wombat
# - tomorrow_night
# - taerminal
# - remedy_dark
# - monokai_pro
# - kanagawa_dragon
# - kanagawa_wave
# - everforest_dark
# - gruvbox_dark
# - gruvbox_material_hard_dark
#
# CONTRAST COLORS:
#
# - ayu_dark
#
# VIVID:
#
# - catppuccin_mocha
# - enfocado_dark
# - rose_pine
# - palenight
# - night_owl
#
# GREY:
#
# - doom_one 
# - nordic
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"


[window]
padding.x = 2
padding.y = 2

decorations = "Full" # Full, Transparent, Buttonless, None
opacity = 0.92
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 15.0

[shell]
program = "/bin/zsh"
